apiVersion: apps/v1
kind: Deployment
metadata:
  name: ichimoku-backend
  labels:
    app: ichimoku-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ichimoku-backend
  template:
    metadata:
      labels:
        app: ichimoku-backend
    spec:
      containers:
      - name: backend
        image: ichimoku-cloud-streamlit-backend:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"