apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: ichimoku-backend
spec:
  type: NodePort
  selector:
    app: ichimoku-backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30000
    protocol: TCP