version: '3'

services:
  streamlit-frontend:
    build: ./streamlit-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - ichimoku-network

  react-frontend:
    build: ./react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ichimoku-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - ichimoku-network

networks:
  ichimoku-network:
    driver: bridge