version: '3'

services:
  streamlit-frontend:
    build: ./streamlit-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - ichimoku-network

  react-frontend:
    build: ./react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ichimoku-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - USE_AWS_S3=${USE_AWS_S3}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - USE_AWS_LAMBDA=${USE_AWS_LAMBDA}
      - USE_AWS_CLOUDWATCH=${USE_AWS_CLOUDWATCH}
    volumes:
      - ~/.aws:/root/.aws:ro  # Mount AWS credentials (read-only)
    networks:
      - ichimoku-network

networks:
  ichimoku-network:
    driver: bridge