apiVersion: v1
kind: Service
metadata:
  name: streamlit-frontend-service
  labels:
    app: ichimoku-streamlit-frontend
spec:
  type: NodePort
  selector:
    app: ichimoku-streamlit-frontend
  ports:
  - name: http
    port: 8501
    targetPort: 8501
    nodePort: 30001
    protocol: TCP