apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
  labels:
    app: ichimoku-react-frontend
spec:
  type: NodePort
  selector:
    app: ichimoku-react-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30002
    protocol: TCP