apiVersion: apps/v1
kind: Deployment
metadata:
  name: ichimoku-react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ichimoku-react-frontend
  template:
    metadata:
      labels:
        app: ichimoku-react-frontend
    spec:
      containers:
      - name: react-frontend
        image: ichimoku-cloud-streamlit-react-frontend:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent