name: Build Docker images

# When to run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # 1) Grab your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Enable Docker Buildx (for faster, more powerful builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3) Build the backend image (tags it for local use in Kubernetes too)
      - name: Build backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          tags: ichimoku-cloud-streamlit-backend:latest
          push: false

      # 4) Build the frontend image
      - name: Build frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          tags: ichimoku-cloud-streamlit-frontend:latest
          push: false
